version: '3.7'

services:
  tomcat:
    ports:
      - "8000:8000"
    environment:
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket
    entrypoint: /usr/local/tomcat/bin/catalina.sh jpda run
