version: '3.7'

## BASE VALUES (reused in the services)
x-tomcat: &tomcat
  image: tomcat:jdk8
  restart: unless-stopped
  ports:
    - "4000-4100:8080"
#  volumes:
#    # difference?! exploded seems more speedy
#    - ./target/pollweb.war:/usr/local/tomcat/webapps/sose-1920.war
#    - ./microservices/person/target/sose:/usr/local/tomcat/webapps/sose
#  environment:
#    # env parameters for java app (not used for now)
#    JDBC_URL: jdbc:mysql://mariadb:3306/sosedb?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
#    JDBC_USER: sose
#    JDBC_PASS: sose

x-mariadb: &mariadb
  image: mariadb:10.5.1
  restart: unless-stopped
  environment:
    # or set more detailed access policy in docker/db-init.sql
    MYSQL_ROOT_PASSWORD: sose
    MYSQL_DATABASE: sosedb
    MYSQL_USER: sose
    MYSQL_PASSWORD: sose

x-eureka: &eureka
  EUREKA_SERVER_URI: ${EUREKA_SERVER_URI}
  EUREKA_SERVER_PORT: '8080'
  EUREKA_BASE_PATH: ''

## SERVICES
services:

  frontend:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./frontend/docker/dist:/usr/share/nginx/html
      - ./frontend/docker/ngnix.frontend.conf:/etc/nginx/conf.d/ngnix.wyw.template
    ports:
      - "3000:80"
      - "3443:443"
    environment:
      NGINX_HOST: ${FRONTEND_HOST:-localhost}
    command: /bin/ash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/ngnix.wyw.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  # PERSON MS (inherit from base microservice)
  person-ws:
    <<: *tomcat
    depends_on:
      - person-db
    volumes:
      - ./microservices/person/target/sose:/usr/local/tomcat/webapps/ROOT
    environment: *eureka
    networks:
      - microservices

  person-db:
    <<: *mariadb
    volumes:
      # only naming/label volume ("docker-compose down -v" to erase)
      - person-db-data:/var/lib/mysql
      # executing only on create container (first "docker-compose up")
      - ./microservices/person/db/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - microservices

  film-ws:
    <<: *tomcat
    depends_on:
      - film-db
    volumes:
      - ./microservices/film/target/sose:/usr/local/tomcat/webapps/ROOT
    environment:
      <<: *eureka
      OMDB_API_KEY: ${OMDB_API_KEY}
    networks:
      - microservices

  film-db:
    <<: *mariadb
    volumes:
      # only naming/label volume ("docker-compose down -v" to erase)
      - film-db-data:/var/lib/mysql
      # executing only on create container (first "docker-compose up")
      - ./microservices/film/db/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - microservices

  user-ws:
    <<: *tomcat
    depends_on:
      - user-db
    volumes:
      - ./microservices/user/target/sose:/usr/local/tomcat/webapps/ROOT
    environment: *eureka
    networks:
      - microservices

  user-db:
    <<: *mariadb
    volumes:
      # only naming/label volume ("docker-compose down -v" to erase)
      - user-db-data:/var/lib/mysql
      # executing only on create container (first "docker-compose up")
      - ./microservices/user/db/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - microservices

  watched-film-ws:
    <<: *tomcat
    depends_on:
      - watched-film-db
    volumes:
      - ./microservices/watched-film/target/sose:/usr/local/tomcat/webapps/ROOT
    environment:
      <<: *eureka
      OMDB_API_KEY: ${OMDB_API_KEY}
    networks:
      - microservices

  watched-film-db:
    <<: *mariadb
    volumes:
      # only naming/label volume ("docker-compose down -v" to erase)
      - watched-film-db-data:/var/lib/mysql
      # executing only on create container (first "docker-compose up")
      - ./microservices/watched-film/db/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - microservices

  eureka-registry:
    <<: *tomcat
    ports:
      - "8761:8080"
    volumes:
      - ./microservices/eureka-registry/target/sose:/usr/local/tomcat/webapps/ROOT
    environment:
      HOSTNAME: ${EUREKA_SERVER_URI}
    networks:
      - microservices

  zuul-proxy:
    <<: *tomcat
    ports:
      - "8762:8080"
    volumes:
      - ./microservices/zuul/target/sose:/usr/local/tomcat/webapps/ROOT
    environment: *eureka
    networks:
      - microservices

  adminer:
    # use for disable any service
    #build: './utils/docker-disable'
    #image: disable:1.0
    image: adminer:4.7.6
    restart: unless-stopped
    environment:
      # https://www.adminer.org/en/plugins/
      ADMINER_PLUGINS: 'file-upload tinymce'
      ADMINER_DEFAULT_SERVER: 'person-db'
    ports:
      - "5000:8080"
    networks:
      - microservices

networks:
  microservices:

volumes:
  person-db-data:
  film-db-data:
  user-db-data:
  watched-film-db-data: