server:
  port: ${PORT:8080}

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/sose/eureka/
  server:
    #waitTimeInMsWhenSyncEmpty: 0

