eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${PORT:8080}/sose/eureka/
  server:
    #waitTimeInMsWhenSyncEmpty: 0

