management.security.enabled: false

cxf:
  path: /
  servlet.init:
    service-list-path: info
  jaxrs:
    component-scan: true
    classes-scan-packages: org.apache.cxf.jaxrs.swagger,org.apache.cxf.metrics


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_URI:eureka-registry}:${EUREKA_SERVER_PORT:8080}${EUREKA_BASE_PATH:/sose}/eureka/
  instance:
    prefer-ip-address: true
    statusPageUrlPath: ${cxf.path}/${cxf.servlet.init.service-list-path}
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadataMap:
      servletPath: ${cxf.path}
#    ## UNCOMMENT THIS TO MAKE FASTER TO REGISTER AND EXPIRE INSTANCES IN EUREKA
#    ## Default settings are recommended by Spring on production
#    ## how often heartbreak is sent. Default is 30s
#    leaseRenewalIntervalInSeconds: 1
#    ## how long to wait after heartbreak is not sent to expire the instance. Default is 90s
#    leaseExpirationDurationInSeconds: 2

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:mariadb://watched-film-db:3306/sosedb'
    username: sose
    password: sose
    driver-class-name: 'org.mariadb.jdbc.Driver'
    hikari:
      minIdle: 10
      idle-timeout: 10000
      maximumPoolSize: 30

management.endpoints.web.exposure.include: health, info, metrics

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000000
            strategy: THREAD

# This is needed if you want to see OMDB request in logs.
logging.level.it.univaq.sose.film.client.OmdbServiceClient: DEBUG
