# Zuul Proxy will be up and running on port 2020.
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_URI:eureka-registry}:${EUREKA_SERVER_PORT:8080}${EUREKA_BASE_PATH:/sose}/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Unique id for multiple instances

# Mapping with different services by using name.
zuul:
  routes:
      hello-service:
        path: /hello-api/**
        serviceId: jaxrs-hello-world-service