eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_URI:eureka-registry}:${EUREKA_SERVER_PORT:8080}${EUREKA_BASE_PATH:/sose}/eureka/
  instance:
    prefer-ip-address: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Unique id for multiple instances

# Mapping with different services by using name.
zuul:
  routes:
      hello-service:
        path: /hello/**
        serviceId: jaxrs-hello-world-service
        stripPrefix: true
      film-service:
        path: /filmservice/**
        serviceId: film-service
        stripPrefix: true
      user-service:
        path: /userservice/**
        serviceId: user-service
        stripPrefix: true
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000
  ribbon:
    eager-load:
      enabled: true

hystrix:
  command:
    film-service:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000


film-service:
  ribbon:
    ReadTimeout: 800
    ConnectTimeout: 250
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 0