eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_URI:eureka-registry}:${EUREKA_SERVER_PORT:8080}${EUREKA_BASE_PATH:/sose}/eureka/
  instance:
    prefer-ip-address: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Unique id for multiple instances

# Mapping with different services by using name.
zuul:
  routes:
    hello-service:
      path: /hello/**
      serviceId: jaxrs-hello-world-service
      stripPrefix: true
    film-service:
      path: /filmservice/**
      serviceId: film-ws
      stripPrefix: true
    user-service:
      path: /userservice/**
      serviceId: user-ws
      stripPrefix: true
  host:
    max-total-connections: 1000
    max-per-route-connections: 100
    connect-timeout-millis: 90000
    socket-timeout-millis: 90000
  semaphore.max-semaphores: 500


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000000
            strategy: THREAD

ribbon:
  ReadTimeout: 60000