management.security.enabled: false

cxf:
  path: /proxyservice
  servlet.init:
    service-list-path: /info
  jaxrs:
    component-scan: true
    classes-scan-packages: org.apache.cxf.jaxrs.swagger,org.apache.cxf.metrics

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone:  http://${EUREKA_SERVER_URI:eureka-registry}:${EUREKA_SERVER_PORT:8080}${EUREKA_BASE_PATH:/sose}/eureka/
  instance:
    prefer-ip-address: true
    statusPageUrlPath: ${EUREKA_BASE_PATH:/sose}${cxf.path}/info
    healthCheckUrlPath: ${EUREKA_BASE_PATH:/sose}/actuator/health
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      servletPath: ${cxf.path}
#    ## UNCOMMENT THIS TO MAKE FASTER TO REGISTER AND EXPIRE INSTANCES IN EUREKA
#    ## Default settings are recommended by Spring on production
#    ## how often heartbreak is sent. Default is 30s
#    leaseRenewalIntervalInSeconds: 1
#    ## how long to wait after heartbreak is not sent to expire the instance. Default is 90s
#    leaseExpirationDurationInSeconds: 2

endpoints:
  jmx:
    enabled: true
    unique-names: true